### ISSUE TITLE
Browse file no show

### ISSUE THREAD

**Issue by truefriend-cz** [mantisbt-plugins/releasemgt#9]
On project release for uploading file no show Browse button for selecting upload file.

mantis 2.19.0

**Comment by kjorsh** [comment]
Sorry missed this completely. Is it still an issue? Could you be more specific so I can try to reproduce:
1. Screenshot will be useful
2. Browser used

**Comment by King-GO** [comment]
same issue with MantisBT 2.22.0
![rls-1](https://user-images.githubusercontent.com/54804407/68445782-d89da400-0215-11ea-8666-23dbd261d3fe.png)

without product version input, upload the file show below
![rls-2](https://user-images.githubusercontent.com/54804407/68445802-e5ba9300-0215-11ea-9c50-3026bc848150.png)

confirm file is uploaded, then click the menu shows below
![rls-3](https://user-images.githubusercontent.com/54804407/68445817-ef43fb00-0215-11ea-9547-c7b53a68acb0.png)

**Comment by kjorsh** [comment]
I am not sure I understand your reference "same issue with MantisBT 2.22.0". There not supposed to be any "Browse" button available for uploaded files. Just a link to download. Is it a real issue - absence of a link to download for the file uploaded without "Product version"?

I will take a look. My guess it was not designed for files without version. It should not be a a big deal to add this feature.

**Comment by kjorsh** [comment]
Actually there is two independent issues:
1. Browse/Choose File (depend on Mantis version and so language resources) button is missing when project not configured and should use default number of upload files
![ReleaseMgmt-missing-button](https://user-images.githubusercontent.com/27141627/68551210-7b058500-03d8-11ea-9ae8-f80859ea7a2e.PNG)
2. Error when upload file with no "Product version" selected
